/**
 * registry.json  →  src/generated/registry.gen.ts
 *
 * Emits literal-union types for every ID in the registry. Code that references an ID that
 * does not exist fails to COMPILE; a registered skill without an implementation fails to COMPILE.
 *
 *   npm run registry:codegen          write the file
 *   npm run registry:codegen -- --check   fail (exit 1) if the committed file is stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";

const SRC = "registry/registry.json";
const OUT = "src/generated/registry.gen.ts";

const raw = readFileSync(SRC, "utf8");
const reg = JSON.parse(raw);
const hash = createHash("sha256").update(JSON.stringify(reg)).digest("hex").slice(0, 16);

const lit = (xs: readonly unknown[]): string =>
  xs.length ? [...new Set(xs)].map((x) => JSON.stringify(x)).join(" | ") : "never";
const arr = (xs: readonly unknown[]): string => `[${[...new Set(xs)].map((x) => JSON.stringify(x)).join(", ")}] as const`;

const signals = reg.signals as { id: string; domain: (string | number)[] }[];
const skills = reg.skills as { id: string; strategies: { id: string }[] }[];
const strategyKeys = skills.flatMap((s) => s.strategies.map((st) => `${s.id}.${st.id}`));
const reasons = (reg.hardRules as { reason: string }[]).map((h) => h.reason);
const policyIds = Object.values(reg.policies as Record<string, { id: string }[]>).flat().map((p) => p.id);

const out = `/* eslint-disable */
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/registry-codegen.ts — DO NOT EDIT BY HAND.
// Source of truth: ${SRC}
// ─────────────────────────────────────────────────────────────────────────────

export const REGISTRY_HASH = ${JSON.stringify(hash)};
export const REGISTRY_VERSION = ${JSON.stringify(reg.meta.registryVersion)};

export type Band = ${lit(reg.bands.map((b: { id: string }) => b.id))};
export type NonP0Band = Exclude<Band, "P0">;
export type Source = ${lit(reg.sources)};

export type SignalId = ${lit(signals.map((s) => s.id))};
export const SIGNAL_IDS = ${arr(signals.map((s) => s.id))};

/** Value domain of each signal. "unknown" is always a legal value. */
export interface SignalDomain {
${signals.map((s) => `  ${s.id}: ${lit(s.domain)};`).join("\n")}
}

export type QuestionId = ${lit(reg.questions.map((q: { id: string }) => q.id))};
export type CardId = ${lit(reg.cards.map((c: { id: string }) => c.id))};
export type SkillId = ${lit(skills.map((s) => s.id))};
export const SKILL_IDS = ${arr(skills.map((s) => s.id))};
export type StrategyKey = ${lit(strategyKeys)};
export type CommitmentKind = ${lit(reg.commitments.map((c: { id: string }) => c.id))};
export type HardRuleId = ${lit(reg.hardRules.map((h: { id: string }) => h.id))};
export type HardRuleReason = ${lit(reasons)};
export type BandRuleId = ${lit(reg.bandRules.map((b: { id: string }) => b.id))};
export type PolicyRuleId = ${lit(policyIds)};
export type TextTriggerId = ${lit(reg.textTriggers.rules.map((t: { id: string }) => t.id))};
export type InvariantId = ${lit(reg.invariants.map((i: { id: string }) => i.id))};
export type ChipId = ${lit(reg.chips.map((c: { id: string }) => c.id))};
export type EventId = ${lit(reg.events.map((e: { id: string }) => e.id))};
export type RiskDimension = ${lit(reg.risk.dimensions)};
export type HandoffTarget = ${lit(Object.keys(reg.regions[reg.meta.region].numbers).concat(["trusted"]))};
export type Requirement = ${lit(Object.keys(reg.requirements).filter((k) => k !== "doc"))};
export type LawId = ${lit(reg.laws.map((l: { id: string }) => l.id))};
export type JournalKind = ${lit(reg.continuity.journalKinds.map((k: { id: string }) => k.id))};
export const JOURNAL_KINDS = ${arr(reg.continuity.journalKinds.map((k: { id: string }) => k.id))};
export type Provenance = ${lit(reg.continuity.provenance)};
export type ShareAudience = ${lit(Object.keys(reg.continuity.share.audiences))};
export type AccessScope = ${lit([...new Set([...Object.values(reg.continuity.share.audiences as Record<string, string[]>).flat(), ...reg.continuity.share.optionalScopes])])};
export type RecencyBucket = ${lit(Object.keys(reg.continuity.buckets).filter((k) => k !== "doc"))};
`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== out) {
    console.error(`✖ ${OUT} is stale. Run: npm run registry:codegen`);
    process.exit(1);
  }
  console.log(`✔ ${OUT} is up to date (registry ${hash})`);
} else {
  writeFileSync(OUT, out);
  console.log(`✔ wrote ${OUT} (registry ${hash})`);
}
